name: Update translations

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/Checkout@v3
      - name: Pull latest translations
        uses: crowdin/github-action@1.4.9
        with:
          upload_translations: false
          download_translations: true
          crowdin_branch_name: "github"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
