name: Push to Crowdin

on:
  push:
    branches:
      - "master"
    paths:
      - "src/main/resources/lang/en.json"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Push to Crowdin
        uses: crowdin/github-action@1.4.9
        with:
          upload_translations: true
          download_translations: false
          crowdin_branch_name: "github"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
        
